---

- name: Install aptitude
  apt: name=aptitude state=installed

- name: Update all packages to the latest version
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day