# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - ./rules/rules.yml
    - ./rules/rules_dev.yml
    - ./rules/all_linux_nodes.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'Alert_Manager'

    static_configs:
    - targets: ['alertmanager:9093']

  - job_name: Hub-Dev

    static_configs:
    - targets: ['hub-dev.pfs-management.com:9100']
    - targets: ['hub-dev.pfs-management.com:8080']


  - job_name: Hub-Stage

    static_configs:
    - targets: ['stage-digital-hub.dpn.gov.uk:9100']
    - targets: ['stage-digital-hub.dpn.gov.uk:8080']

  - job_name: Hub-Wayland-Prod-1

    static_configs:
    - targets: ['digital-hub.wli.dpn.gov.uk:9100']
    - targets: ['digital-hub.wli.dpn.gov.uk:8080']

  - job_name: Hub-Berwyn-Prod-1

    static_configs:
    - targets: ['digital-hub.bwi.dpn.gov.uk:9100']
    - targets: ['digital-hub.bwi.dpn.gov.uk:8080']
    
  - job_name: Grafana

    static_configs:
    - targets: ['grafana:3000']

  - job_name: 'cadvisor'
    scrape_interval: 5s

    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://hub-dev.pfs-management.com
        - https://pfs-stage-hub-1.uksouth.cloudapp.azure.com
        - https://digital-hub.wli.dpn.gov.uk
        - https://digital-hub.bwi.dpn.gov.uk
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115