# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - ./rules/rules.yml
    - ./rules/rules_dev.yml
    - ./rules/all_linux_nodes.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'Alert_Manager'

    static_configs:
    - targets: ['alertmanager:9093']

  - job_name: Hub-Dev

    static_configs:
    - targets: ['hub-dev.pfs-management.com:9100']
    - targets: ['hub-dev.pfs-management.com:8080']


  - job_name: Hub-Stage

    static_configs:
    - targets: ['stage-digital-hub.dpn.gov.uk:9100']
    - targets: ['stage-digital-hub.dpn.gov.uk:8080']

  - job_name: Hub-Wayland-Prod-1

    static_configs:
    - targets: ['digital-hub.wli.dpn.gov.uk:9100']
    - targets: ['digital-hub.wli.dpn.gov.uk:8080']

  - job_name: Hub-Berwyn-Prod-1

    static_configs:
    - targets: ['digital-hub.bwi.dpn.gov.uk:9100']
    - targets: ['digital-hub.bwi.dpn.gov.uk:8080']

  - job_name: Berwyn-Prod-Windows

    static_configs:
    - targets: ['pfs-prd-bwi-dc1.bwi.dpn.gov.uk:9182']
    - targets: ['pfs-prd-bwi-dc2.bwi.dpn.gov.uk:9182']
    - targets: ['bwisulws001.bwi.dpn.gov.uk:9182']
    - targets: ['bwisulws002.bwi.dpn.gov.uk:9182']
    - targets: ['bwisulws003.bwi.dpn.gov.uk:9182']
    - targets: ['bwismssq002.bwi.dpn.gov.uk:9182']
    - targets: ['bwisulns001.bwi.dpn.gov.uk:9182']
    - targets: ['bwispifs001.bwi.dpn.gov.uk:9182']
    - targets: ['bwisulap001.bwi.dpn.gov.uk:9182']
    - targets: ['bwiddccf001.bwi.dpn.gov.uk:9182']
    - targets: ['bwiddccf002.bwi.dpn.gov.uk:9182']
    - targets: ['bwisdhcp001.bwi.dpn.gov.uk:9182']
    - targets: ['bwiscaen001.bwi.dpn.gov.uk:9182']
    - targets: ['bwismssq001.bwi.dpn.gov.uk:9182']
    - targets: ['bwiscmpr001.bwi.dpn.gov.uk:9182']
    - targets: ['bwissepm002.bwi.dpn.gov.uk:9182']
    - targets: ['bwiscvcs001.bwi.dpn.gov.uk:9182']
    - targets: ['bwisloap001.bwi.dpn.gov.uk:9182']
    - targets: ['bwisloap002.bwi.dpn.gov.uk:9182']
    - targets: ['bwishyph001.bwi.dpn.gov.uk:9182']

  - job_name: Wayland-Prod-Windows

    static_configs:
    - targets: ['pfs-prd-wli-dc1.wli.dpn.gov.uk:9182']
    - targets: ['pfs-prd-wli-dc2.wli.dpn.gov.uk:9182']
    - targets: ['wlisulws001.wli.dpn.gov.uk:9182']
    - targets: ['wlisulws002.wli.dpn.gov.uk:9182']
    - targets: ['wlisulws003.wli.dpn.gov.uk:9182']
    - targets: ['wlismssq002.wli.dpn.gov.uk:9182']
    - targets: ['wlisulns001.wli.dpn.gov.uk:9182']
    - targets: ['wlispifs001.wli.dpn.gov.uk:9182']
    - targets: ['wliddccf001.wli.dpn.gov.uk:9182']
    - targets: ['wliddccf002.wli.dpn.gov.uk:9182']
    - targets: ['wlisdhcp001.wli.dpn.gov.uk:9182']
    - targets: ['wliscaen001.wli.dpn.gov.uk:9182']
    - targets: ['wlismssq001.wli.dpn.gov.uk:9182']
    - targets: ['wlissepm002.wli.dpn.gov.uk:9182']
    - targets: ['wliscvcs001.wli.dpn.gov.uk:9182']
    - targets: ['wlisloap001.wli.dpn.gov.uk:9182']
    - targets: ['wlisloap002.wli.dpn.gov.uk:9182']
    - targets: ['wlishyph001.wli.dpn.gov.uk:9182']


  - job_name: Grafana

    static_configs:
    - targets: ['grafana:3000']

  - job_name: 'cadvisor'
    scrape_interval: 5s

    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://hub-dev.pfs-management.com
        - https://pfs-digital-hub-stage.hmpps.dsd.io
        - https://digital-hub.wli.dpn.gov.uk
        - https://digital-hub.bwi.dpn.gov.uk
        - http://pfs-management-bastion-1.uksouth.cloudapp.azure.com/feeback
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115