
---

hub_sites:
  - upstream_name: hub_node
    upstream_port: 10001
    domain: "{{ hub_frontend_host }}"
  - upstream_name: hub_fe
    upstream_port: 10002
    domain: "{{ hub_frontend_host }}"
  - upstream_name: hub_be
    upstream_port: 11001
    domain: "{{ hub_backend_host }}"


