---

  - name: Add Docker GPG key.
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 0EBFCD88
      state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Add Docker repository.
    get_url:
      url: 'https://download.docker.com/linux/centos/docker-ce.repo'
      dest: '/etc/yum.repos.d/docker-ce.repo'
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Ensure docker is installed
    package:
      name: docker-ce
      state: present

  - name: Ensure docker is enabled and running
    service:
      name: docker
      enabled: yes
      state: started


  # requirement for ansible docker modules to work
  - name: Install python pip
    package:
      name: python-pip
      state: present
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Install python pip
    package:
      name: python-pip
      state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install pip docker library
    pip:
      name: docker

  - name:    Install prerequisites
    become: true
    apt:     name={{item}} update_cache=yes
    with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
     
  - name:    Add Docker GPG key
    become: true
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  - name:    Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  - name:    Install Docker
    apt:     name=docker-ce

  - name: Download docker compose latest and install
    shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  - name: Modify permissions for docker-compose
    shell: sudo chmod +x /usr/local/bin/docker-compose

  - name: Create esdata share for elasticsearch
    become: true
    file:
      path: /data/esdata
      owner: 1000
      group: 1000
      state: directory

  - name: Modify permissions for elasticsearch
    become: true
    shell: chown 1000:1000 -R /data/esdata
  
  - name: Set memory for elastic
    become: true
    shell: sysctl -w vm.max_map_count=262144 

