version: "3"

services:
  hub-db:
    container_name: hub-db
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=hubdb
      - MYSQL_USER=hubdb_user
      - MYSQL_PASSWORD
    volumes:
      - ./db/dump/:/docker-entrypoint-initdb.d

  hub-node:
    container_name: hub-node
    image: "mojdigitalstudio/digital-hub-node:${IMAGE_VERSION}"
    user: "node"
    working_dir: /home/node/app
    depends_on:
      - hub-be
    environment:
      HUB_API_ENDPOINT: http://hub-be
      APP_TIMEOUT: 60.0
      PORT: 3000
      APP_NAME: HMP Dev
      ELASTICSEARCH_ENDPOINT: http://hub-elasticsearch:9200
      BACKEND_URL: http://hub-be

  hub-be:
    container_name: hub-be
    image: mojdigitalstudio/digital-hub-be
    depends_on:
      - hub-db
    environment:
      - HUB_DB_ENV_MYSQL_DATABASE=hubdb
      - HUB_DB_ENV_MYSQL_USER=hubdb_user
      - HUB_DB_ENV_MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - HUB_DB_PORT_3306_TCP_ADDR=hub-db
      - HUB_EXT_FILE_URL=http://localhost:11001/sites/default/files
      - PHP_MEMORY_LIMIT=256M
      - PHP_UPLOAD_MAX_FILE_SIZE=500M
      - PHP_POST_MAX_SIZE=500M
      - XDEBUG_IP=127.0.0.1 # Replace with your machines IP: $ ipconfig getifaddr en0
    ports:
      - 11001:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 30s
      retries: 1

  hub-elasticsearch:
    container_name: hub-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  nginx:
    image: nginx:stable
    container_name: production_nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - hub-node
      - hub-be
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: "always"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
