---

- name: Copy daily backup cron job into place
  become: true
  copy:
    src: ../hub-containers/db/docker-backup.sh
    dest: /etc/cron.daily/docker-backup.sh
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Changing perm of "/etc/docker-backup", adding "+x"
  become: true
  file: dest=/etc/cron.daily/docker-backup.sh mode=a+x


- name: Database backup job
  become: true
  cron:
    name: "Backup MYSQL databases"
    minute: "00"
    hour: "01"
    weekday: "0-6"
    job: "/etc/cron.daily/docker-backup.sh"
    disabled: "no"
    state: present
  tags:
   - cronjobs

- name: check for line breaks (windows issue)
  become: true
  shell: sed -i -e 's/\r$//' /etc/cron.daily/docker-backup.sh


  #####

- name: Copy scheduled release cron job into place
  become: true
  copy:
    src: ../hub-containers/db/release-schedule.sh
    dest: /etc/cron.d/release-schedule.sh
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Changing perm of "/etc/release-schedule", adding "+x"
  become: true
  file: dest=/etc/cron.d/release-schedule.sh mode=a+x


- name: release-schedule
  become: true
  cron:
    name: "release-schedule 8am"
    minute: "00"
    hour: "07" #servers are in UTC
    job: "/etc/cron.d/release-schedule.sh"
    disabled: "no"
    state: present
  tags:
   - cronjobs

- name: release-schedule
  become: true
  cron:
    name: "release-schedule 4pm"
    minute: "00"
    hour: "15" #servers are in UTC
    job: "/etc/cron.d/release-schedule.sh"
    disabled: "no"
    state: present
  tags:
   - cronjobs

- name: check for line breaks (windows issue)
  become: true
  shell: sed -i -e 's/\r$//' /etc/cron.d/release-schedule.sh


  ###

- name: Copy clear down  cron job into place
  become: true
  copy:
    src: ../hub-containers/files/cleardown-docker-images.sh
    dest: /etc/cron.daily/cleardown-docker-images.sh
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Changing perm of "/etc/cleardown-docker-images.sh", adding "+x"
  become: true
  file: dest=/etc/cron.daily/cleardown-docker-images.sh mode=a+x

  
- name: docker image clear down job
  become: true
  cron:
    name: "docker image clear down job"
    minute: "00"
    hour: "02"
    weekday: "0-6"
    job: "/etc/cron.daily/cleardown-docker-images.sh"
    disabled: "no"
    state: present
  tags:
   - cronjobs

- name: check for line breaks (windows issue)
  become: true
  shell: sed -i -e 's/\r$//' /etc/cron.daily/cleardown-docker-images.sh
