---

- name: Copy daily backup cron job into place
  become: true
  copy:
    src: ../hub-containers/db/docker-backup.sh
    dest: /etc/cron.daily/docker-backup.sh
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
   - cronjobs
   
- name: Changing perm of "/etc/docker-backup", adding "+x"
  become: true
  file: dest=/etc/cron.daily/docker-backup.sh mode=a+x
  tags:
   - cronjobs

- name: Database backup job
  become: true
  cron:
    name: "Backup MYSQL databases"
    minute: "00"
    hour: "01"
    weekday: "0-6"
    job: "/etc/cron.daily/docker-backup.sh"
    disabled: "no"
    state: present
  tags:
   - cronjobs

- name: check for line breaks (windows issue)
  become: true
  shell: sed -i -e 's/\r$//' /etc/cron.daily/docker-backup.sh
  tags:
   - cronjobs

  #####

- name: Copy scheduled release cron job into place
  become: true
  copy:
    src: ../hub-containers/db/release-schedule.sh
    dest: /etc/cron.d/release-schedule.sh
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
   - cronjobs

- name: Changing perm of "/etc/release-schedule", adding "+x"
  become: true
  file: dest=/etc/cron.d/release-schedule.sh mode=a+x
  tags:
   - cronjobs

- name: release-schedule
  become: true
  cron:
    name: "release-schedule 8am"
    minute: "00"
    hour: "07" #servers are in UTC
    job: "/etc/cron.d/release-schedule.sh"
    disabled: "no"
    state: present
  tags:
   - cronjobs

- name: release-schedule
  become: true
  cron:
    name: "release-schedule 4pm"
    minute: "00"
    hour: "15" #servers are in UTC
    job: "/etc/cron.d/release-schedule.sh"
    disabled: "no"
    state: present
  tags:
   - cronjobs

- name: check for line breaks (windows issue)
  become: true
  shell: sed -i -e 's/\r$//' /etc/cron.d/release-schedule.sh
  tags:
   - cronjobs

  ###

- name: Copy clear down  cron job into place
  become: true
  copy:
    src: ../hub-containers/files/cleardown-docker-images.sh
    dest: /etc/cron.daily/cleardown-docker-images.sh
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
   - cronjobs

- name: Changing perm of "/etc/cleardown-docker-images.sh", adding "+x"
  become: true
  file: dest=/etc/cron.daily/cleardown-docker-images.sh mode=a+x
  tags:
   - cronjobs
  
- name: docker image clear down job
  become: true
  cron:
    name: "docker image clear down job"
    minute: "00"
    hour: "02"
    weekday: "0-6"
    job: "/etc/cron.daily/cleardown-docker-images.sh"
    disabled: "no"
    state: present
  tags:
   - cronjobs

- name: check for line breaks (windows issue)
  become: true
  shell: sed -i -e 's/\r$//' /etc/cron.daily/cleardown-docker-images.sh
  tags:
   - cronjobs
##adding these jobs as the fstab is randomly failing on timeouts. This is a consistent

- name: Creates an entry "@reboot sudo mount /mnt/pfs-prod-digital-hub-content-share"
  cron:
    name: "post reboot map the content drive"
    special_time: reboot
    job: "sudo mount /mnt/pfs-prod-digital-hub-content-share"
  tags:
   - cronjobs

#Additional fail safe job. 

- name: Copy clear down  cron job into place
  become: true
  copy:
    src: ../hub-containers/files/mount-checker.sh
    dest: /etc/cron.hourly/mount-checker.sh
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
   - cronjobs

- name: Check if the mount is present and remount it, then restart the hub-be backend container post
  become: true
  cron:
    name: "check mount, restart hub-be"
    minute: "*/5"
    hour: "*"
    weekday: "*"
    job: "/etc/cron.hourly/mount-checker.sh"
    disabled: "no"
    state: present
  tags:
   - cronjobs

   
- name: check for line breaks (windows issue)
  become: true
  shell: sed -i -e 's/\r$//' /etc/cron.hourly/mount-checker.sh
  tags:
   - cronjobs

- name: Modify permissions
  shell: sudo chmod +x /etc/cron.hourly/mount-checker.sh
  tags:
   - cronjobs
  