---
#base line for the host
- name: baseline
  hosts: all
  become: true
  roles:
    - base
    - jnv.unattended-upgrades
    - role: singleplatform-eng.users
      tags:
      - users
    - provisioning # This will cause the intial run to fail due to deleting the hub user

- hosts: stage, prod
  become: true
  roles: 
    - dockerinstall #broke out due to some issue with Dev, if rebuilding dev this will need to be run

    #builds the docker and container config
- hosts: all
  roles:
    - hub-containers
    - docker
  tags: containers


- hosts: all
  become: true
  roles:
    - role: undergreen.prometheus-node-exporter
      prometheus_node_exporter_version: 0.18.1
      prometheus_node_exporter_enabled_collectors:
        - conntrack
        - cpu
        - diskstats
        - entropy
        - filefd
        - filesystem
        - loadavg
        - mdadm
        - meminfo
        - netdev
        - netstat
        - stat
        - textfile
        - time
        - vmstat
      prometheus_node_exporter_config_flags:
        'web.listen-address': '0.0.0.0:9100'
        'log.level': 'info'
